"""Add fingerprint to poll_answer_votes

Revision ID: 1144862e407c
Revises: 445dc12c6616
Create Date: 2025-12-07 07:26:04.396738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1144862e407c'
down_revision = '445dc12c6616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_answer_votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fingerprint', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_answer_votes', schema=None) as batch_op:
        batch_op.drop_column('fingerprint')

    # ### end Alembic commands ###
